version: '2'
services:
  swag_apache:
    extends:
      file: docker-base.yml
      service: swag_apache
    links:
      - swag_db:mysql
      - swag_smtp:smtp
  swag_cli:
    extends:
      file: docker-base.yml
      service: swag_cli
    links:
      - swag_db:mysql
  swag_smtp:
    extends:
      file: docker-base.yml
      service: swag_smtp
  swag_db:
    extends:
      file: docker-base.yml
      service: swag_db
  swag_pma:
    extends:
      file: docker-base.yml
      service: swag_pma
    links:
      - swag_db:db