#!/usr/bin/env bash

configfile='variables.cfg'

if [ -r $configfile ]; then
  printf "Reading config file $configfile...\n"

  if egrep -q -v '^#|^[^ ]*=[^;]*' "$configfile"; then
    printf "Config file is unclean, exiting.\n"
    exit 1
  fi

  source $configfile
else
  echo -n "Please enter the path to your shopware installation [/home/$USER/Code/shopware]: "
  read SWINSTALL
  echo -n "Please enter the group your files (cache etc.) should belong to [$USER]: "
  read GROUP
fi

if [ -z "$SWINSTALL" ]; then
  	SWINSTALL="/home/$USER/Code/shopware"
fi

if [ -z "$GROUP" ]; then
  	GROUP="$USER"
fi

printf "Setting owner:group recursive to \e[43m\e[30m$USER:$GROUP\e[0m\e[39m in \e[43m\e[30m$SWINSTALL\e[0m\e[39m ...\n"
sudo chown -R $USER:$GROUP $SWINSTALL/

printf "done!\n"
